# Generated by Django 3.0.3 on 2020-03-01 19:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="placeofstudy",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterModelManagers(
            name="placeofwork",
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
