# Generated by Django 3.0.4 on 2020-03-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20200301_1908"),
    ]

    operations = [
        migrations.DeleteModel(name="PlaceOfStudy",),
        migrations.DeleteModel(name="PlaceOfWork",),
    ]
