# Generated by Django 3.0.4 on 2020-03-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="new_user", new_name="user",
        ),
    ]
