# Generated by Django 3.0.4 on 2020-03-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20200321_1341"),
    ]

    operations = [
        migrations.AlterModelOptions(name="tag", options={"ordering": ["title"]},),
        migrations.RemoveField(model_name="post", name="created",),
        migrations.RemoveField(model_name="post", name="status",),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
