# Generated by Django 3.0.5 on 2020-04-26 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0005_auto_20200321_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор - это Вы!)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                blank=True, db_index=True, verbose_name="Основная часть"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="blog.Tag",
                verbose_name="Присвойте метки:",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Рекомендуется присваивать краткий и содержательный заголовок, несмотря на сложность используемых терминов.",
                max_length=500,
                verbose_name="Заголовок публикации:",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="In english, please"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название метки"),
        ),
        migrations.DeleteModel(name="Comment",),
    ]
