# Generated by Django 3.0.5 on 2020-05-06 13:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("blog", "0008_auto_20200502_2308"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorUser",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                related_query_name="post",
                to="blog.AuthorUser",
                verbose_name="Авторство",
            ),
        ),
    ]
