# Generated by Django 3.0.5 on 2020-05-06 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0009_auto_20200506_1340"),
    ]

    operations = [
        migrations.DeleteModel(name="AuthorUser",),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                related_query_name="post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Авторство",
            ),
        ),
    ]
